version: '2'
services:
    mongo-1-1:
        container_name: "mongo-1-1"
        image: mongo:test
        network_mode: "host"
        ports:
            - "30011:27017"
        command: mongod --replSet rs1 --shardsvr --bind_ip 172.16.106.130 --cpu --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always
