version: '2'
services:
    mongo-1-1:
        container_name: "mongo-1-1"
        image: mongo:test
        network_mode: "host"
        ports:
            - "30011:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
#        links:
#            - mongo-1-2:mongo-1-2
#            - mongo-1-3:mongo-1-3
        restart: always
