version: '2'
services:
    mongo-rs1-setup:
        container_name: "mongo-rs1-setup"
        image: mongo:test-5
        network_mode: "host"
#        depends_on:
#            - "mongo-1-1"
#            - "mongo-1-2"
#            - "mongo-1-3"
#        links:
#            - mongo-1-1:mongo-1-1
#            - mongo-1-2:mongo-1-2
#            - mongo-1-3:mongo-1-3
        environment:
            - MONGO1=172.16.106.130
            - MONGO2=172.16.106.131
            - MONGO3=172.16.106.132
            - RS=rs1
        entrypoint: [ "/scripts/setup.sh" ]
