version: '2'
services:
    mongo-1-1:
        container_name: "mongo-1-3"
        image: mongo:test
        network_mode: "host"
        ports:
            - "30011:27017"
        command: mongod --replSet rs1 --shardsvr --cpu --bind_ip 172.16.106.132 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always
